name: Node Ci

on: push

jobs:
  build:
    runs-on: ubunto-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install 

      - name: Complete
        run: echo "All done"
