name: Node Ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20
      COMPLETE_TEXT: ${{secrets.COMPLETE_TEXT}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install deps
        run: npm install 

      - name: Complete
        run: echo $COMPLETE_TEXT
